version: "3.8"

services:
  netgrowth-backend:
    container_name: netgrowth-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - netgrowth-mongo

  netgrowth-mongo:
    container_name: netgrowth-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - netgrowth-mongodata:/data/db

  netgrowth-frontend:
    container_name: netgrowth-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  netgrowth-mongodata:
