version: "3.8"

services:
  netgrowth-app:
    container_name: netgrowth-backend
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/netgrowth
      - /usr/src/netgrowth/node_modules
    depends_on:
      - netgrowth-mongo

  netgrowth-mongo:
    container_name: netgrowth-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - netgrowth-mongodata:/data/db

volumes:
  netgrowth-mongodata:
