version: "3.8"

services:
  netgrowth-backend:
    container_name: netgrowth-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/netgrowth/backend
    depends_on:
      - netgrowth-mongo
    env_file:
      - ./backend/.env
    networks:
      - netgrowth-network

  netgrowth-mongo:
    container_name: netgrowth-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - netgrowth-mongodata:/data/db
    networks:
      - netgrowth-network

  netgrowth-frontend:
    container_name: netgrowth-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/netgrowth/frontend
    networks:
      - netgrowth-network

  netgrowth-backend-test:
    container_name: netgrowth-backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - netgrowth-mongo
    volumes:
      - ./backend:/usr/src/netgrowth/backend
    command: ["npm", "test"]
    env_file:
      - ./backend/.env
    networks:
      - netgrowth-network

volumes:
  netgrowth-mongodata:
networks:
  netgrowth-network:
    driver: bridge
